# -*- coding: utf-8 -*-
{
    'name': 'Studio customizations',
    'version': '13.0.1.0',
    'category': 'Studio',
    'description': u"""
This module has been generated by Odoo Studio.
It contains the apps created with Studio and the customizations of existing apps.
""",
    'author': 'Urban Bonfire Inc.',
    'depends': [
        'account',
        'base',
        'crm',
        'mrp',
        'product',
        'purchase',
        'purchase_stock',
        'sale',
        'sales_team',
        'stock',
        'web_studio',
        'delivery'
    ],
    'data': [
        'data/ir_model_fields.xml',
        'data/ir_ui_view.xml',
        'data/ir_actions_act_window.xml',
        'data/ir_actions_report.xml',
    ],
    'application': False,
    'license': 'OPL-1',
}
